insert into movies values(1,'IP MAN','CHINESE',17:21:38,8.3,9);
insert into movies values(2,'ANDHADHOON','HINDI',14:01:38,9.7,1);
insert into movies values(3,'PARADISE NOW','ARABIC',23:48:06,5.6,5);
insert into movies values(4,'THE INTOUCHBLES ','FRENCH',09:33:43,8.5,8);
insert into movies values(5,'3 IDIOTS','HINDI',16:35:35,9.0,1);
insert into movies values(6,'THE DARK KNIGHT','ENGLISH',14:35:19,9.4,2);
insert into movies values(7,'LEVIATHAN','RUSSIAN',11:39:26,2.6,4);
insert into movies values(8,'SOLARIS','PORTUGESE',06:36:25,6.5,3);
insert into movies values(9,'DON'T WORRY,I'M FINE','SPANISH',05:58:34,0.5,0);
insert into movies values(10,'OMAR','ARABIC',03:06:56,6.0,5);
insert into movies values(11,'SHOLAY','HINDI',00:42:11,7.5,1);
insert into movies values(12,'DON'T WORRY,I'M FINE,'PORTUGESE',01:10:12,0.2,3);
insert into movies values(13,'Au Revoir les Enfants','FRENCH',04:21:38,1.6,8);
insert into movies values(14,'INCEDIES','FRENCH',21:44:44,4.6,8);
insert into movies values(15,'THE ORPHANAGE','SPANISH',19:01:28,1.3,0);

insert into country values(2,'USA');
insert into country values(0,'SPAIN');
insert into country values(9,'CHINA');
insert into country values(1,'INDIA');
insert into country values(4,'RUSSIA');
insert into country values(8,'FRANCE');
insert into country values(3,'PORTUGAL');
insert into country values(5,'UAE');
insert into country values(6,'ITALY');
insert into country values(7,'GERMANY');

insert into roles values(1,'actor');
insert into roles values(2,'actress');
insert into roles values(3,'director');

insert into members values(1,'Ayushmann Khurrana','Ayushmann started off his career as a popular radio jockey, and eventually became a VJ on MTV India and one of the most popular hosts in India. He shot to stardom with the runaway hit, 'Vicky Donor' in 2012. His effortless act in his debut won him rave reviews and the film went on to become one of the biggest hits of the year. ','14-SEP-1984');
insert into members values(2,'Radhika Apte','Radhika Apte is an Indian film and stage actress born in Pune, Maharashtra, India. She is an Economics graduate from Fergusson College, Pune. She is associated with Mohit Takalkar's theatre troupe 'Aasakta' in her hometown. She is the daughter of one of Pune's leading neurosurgeons, Dr. Charu Apte.','7-SEP-1985');
insert into members values(3,'SRIRAM RAGHAVAN','Sriram Raghavan is a writer and director, known for Andhadhun (2018), Badlapur (2015) and Ek Hasina Thi (2004).','25-JUL-1970');
insert into members values(4,'WILSON YIP','Wilson Yip was born as Yip Wai-Shun. He is a director and actor, known for Ip Man (2008), SPL: Kill Zone (2005) and Ip Man 2 (2010).','13-OCT-1981');
insert into members values(5,DONNIE YEN','Donnie Yen was born in Guangzhou, China. His mother, Bow-sim Mark, was a kung fu master and his father, Kylster Yen, a newspaper editor and amateur musician. When Donnie was just two years old, the family moved to Hong Kong and then, when he was 11, to Boston, Massachusetts.','27-JUL-1963');
insert into members values(6,'Lynn Xiong','Lynn Xiong was born in Nanjing, Jiangsu, China as Xiong Dai Ling. She is an actress, known for Ip Man 3 (2015), Ip Man (2008) and Ip Man 2 (2010). She has been married to Ken Kwok since December 2016. ','10-OCT-1981');
insert into members values(7,'BELEN RUEDA','María Belén Rueda García-Porrero (born 16 March 1965) is a Spanish actress. She is best known for her roles as Lucía in the TV series Los Serrano (2003); as Julia in The Sea Inside (2004), for which she won a Goya Award; and as Laura in The Orphanage (2007), for which she received another Goya Award nomination.','16-MAR-1965');
insert into members values(8,'FERNANDO CAYO','Fernando Cayo was born in Valladolid, Valladolid, Castilla y León, Spain as Fernando Cayo Jiménez. He is an actor and casting director, known for The Orphanage (2007), The Skin I Live In (2011) and The Counsellor (2013). ','22-APR-1968');
insert into members values(9,'Denis Villeneuve','Denis Villeneuve is a French Canadian film director and writer. He was born in 1967, in Trois-Rivières, Québec, Canada. He started his career as a filmmaker at the National Film Board of Canada. He is best known for his feature films Arrival (2016), Sicario (2015), Prisoners (2013), Enemy (2013), and Incendies (2010). ','11-APR-1967');
insert into members values(10,'Lubna Azabal','Lubna Azabal was born in Brussels, Belgium. She is an actress, known for Incendies (2010), Coriolanus (2011) and Body of Lies (2008).','12-AUG-1971');
insert into members values(11,'Maxim Gaudette','Maxim Gaudette was born on June 8, 1974 in Sherbrooke, Quebec, Canada. He is an actor, known for Incendies (2010), Polytechnique (2009) and Lac Mystère (2013). ','-8-JUN-1984');
insert into members values(12,'Gaspard Manesse','Gaspard Manesse was born on March 25, 1975. He is an actor and composer, known for Au Revoir les Enfants (1987), Comme il vient (2002) and Erreur de jeunesse (1989).','25-MAR-1987');
insert into members values(13,'Francine Racette','Francine Racette was born on September 23, 1947 in Québec, Canada. She is an actress, known for Au Revoir les Enfants (1987), Lumiere (1976) and Mr. Klein (1976). She has been married to Donald Sutherland since August 1990. They have three children.','23-SEP-1947');
insert into members values(14,'Louis Malle','Louis Malle, the descendant of a French nobleman who made a fortune in beet sugar during the Napoleonic Wars, created films that explored life and its meaning. Malle's family discouraged his early interest in film but, in 1950, allowed him to enter the Institute of Advanced Cinematographic Studies in Paris.','30-OCT-1932');
insert into members values(15,'Hany Abu-Assad','Hany Abu-Assad a Palestinian/Dutch movie director and writer. From the famous Abu-Assad has directed so far Rana's Wedding (2002), Paradise Now (2005) and Omar (2013), The mountains between us (2017). He has been nominated twice for Academy Awards for his movies 'Paradise Now' in 2006 and 'Omar' in 2014.','11-OCT-1961');
insert into members values(16,'Kais Nashif','Kais Nashif is a well known Palestinian actor living in Tel Aviv, Israel with frequent travel to the U.S. Kais is part German from his mother's side and speaks fluent German as well. Languages English, Arabic, Hebrew, German, conversational French, Education: Acting study at "Beit Zvi" the School for Stage Arts.','12-JUN-1978');
insert into members values(17,'FRANCOIS CLUZET','François Cluzet was born on September 21, 1955 in Paris, France. He is an actor, known for The Intouchables (2011), Tell No One (2006) and French Kiss (1995).','21-SEP-1955');
insert into members values(18,'Anne Le Ny','Anne Le Ny was born on December 16, 1962 in Antony, Hauts-de-Seine, France. She is an actress and writer, known for The Intouchables (2011), Those Who Remain (2007) and Family Business (2018). ','16-DEC-1962');
insert into members values(19,'Olivier Nakache','Olivier Nakache was born on April 15, 1973 in Suresnes, Hauts-de-Seine, France. He is a writer and director, known for The Intouchables (2011), C'est la vie! (2017) and Tellement proches (2009).','15-APR-1973');
insert into members values(20,'Rajkumar Hirani','Rajkumar Hirani was born on November 20, 1962 in Nagpur, Maharashtra, India. He is a writer and editor, known for Munna Bhai M.B.B.S. (2003), PK (2014) and 3 Idiots (2009).','20-NOV-1962');
insert into members values(21,'Aamir Khan','Aamir is no doubt one of the most dedicated actors in this world. With his recent success in India and China markets combined he has got the title of Worlds Biggest Superstar. He went through rapid transformations in his body structure for his films to bring out the reality factor in his characters.','14-MAR-1965');
insert into members values(22,'Kareena Kapoor','Kareena was born to Sindhi-speaking Babita (nee Shivdasani) and Punjabi-speaking Randhir Kapoor in Bombay, India. She has an elder sister, Karisma. She is born in a family that have been actors for generations, including her paternal great-grandfather, Prithviraj Kapoor; her grandfather, Raj Kapoor;','20-SEP-1980');
insert into members values(23,'AMITHABH BACHCHAN','Son of well known poet Harivansh Rai Bachchan and Teji Bachchan. He has a brother named Ajitabh. He completed his education from Uttar Pradesh and moved to Bombay to find work as a film star, in vain though, as film-makers preferred someone with a fairer skin, and he was not quite fair enough.','11-OCT-1942');
insert into members values(24,'HEMA MALINI','Hema was born in the Tamil-speaking Chakravarthy household on October 16, 1948 in Ammankudi, Tamil Nadu. Her dad's name is V.S.R. Chakravarthy and her mom, Jaya, was a film producer. She was enrolled in the Chennai-based Andhra Mahila Sabha. ','16-OCT-1948');
insert into members values(25,'Ramesh Sippy','Ramesh Sippy was born on January 23, 1947 in Karachi, Sind Province, British India as Ramesh Gopaldas Sipahimalani. He is a director and producer, known for Sholay (1975), Shaan (1980) and Akayla (1991). He is married to Kiran Juneja.','23-JAN-1947');
insert into members values(26,'Christopher Nolan','Best known for his cerebral, often nonlinear, storytelling, acclaimed writer-director Christopher Nolan was born on July 30, 1970 in London, England. Over the course of 15 years of filmmaking, Nolan has gone from low-budget independent films to working on some of the biggest blockbusters ever made. ','30-JUL-1970');
insert into members values(27,'Maggie Gyllenhaal','Academy Award-nominated actress Maggie Gyllenhaal was born on November 16, 1977, on the Lower East Side of Manhattan in New York City. Her parents, Naomi Foner (née Achs) and Stephen Gyllenhaal, are both filmmakers, and her brother is actor Jake Gyllenhaal. ','16-NOV-1967');
insert into members values(28,'Christian Bale','Christian Charles Philip Bale was born in Pembrokeshire, Wales, UK on January 30, 1974, to English parents Jennifer "Jenny" (James) and David Bale. His mother was a circus performer and his father, who was born in South Africa, was a commercial pilot. The family lived in different countries throughout Bale's childhood, including England, Portugal,Italy,etc.','30-jan-1974');
insert into members values(29,'Adam Bakri','Adam Bakri is an actor, known for Omar (2013), Ali and Nino (2016) and Slam (2018).','19-nov-1983');
insert into members values(30,'Leem Lubany','Leem Lubany is an actress, known for Omar (2013), Condor (2018) and Rock the Kasbah (2015).','31-dec-1984')

insert into cast values(1,5,1);
insert into cast values(1,6,2);
insert into cast values(1,4,3);
insert into cast values(2,1,1);
insert into cast values(2,2,2);
insert into cast values(2,3,3);
insert into cast values(3,16,1);
insert into cast values(3,10,2);
insert into cast values(3,15,3);
insert into cast values(4,17,1);
insert into cast values(4,18,2);
insert into cast values(4,19,3);
insert into cast values(5,20,1);
insert into cast values(5,21,2);
insert into cast values(5,22,3);
insert into cast values(6,28,1);
insert into cast values(6,27,2);
insert into cast values(6,26,3);
insert into cast values(7,17,1);
insert into cast values(7,18,2);
insert into cast values(7,19,3);
insert into cast values(8,5,1);
insert into cast values(8,10,2);
insert into cast values(8,14,3);
insert into cast values(9,9,1);
insert into cast values(9,13,2);
insert into cast values(9,11,3);
insert into cast values(10,29,1);
insert into cast values(10,30,2);
insert into cast values(10,15,3);
insert into cast values(11,23,1);
insert into cast values(11,24,2);
insert into cast values(11,25,3);
insert into cast values(12,8,1);
insert into cast values(12,7,2);
insert into cast values(12,9,3);
insert into cast values(13,11,1);
insert into cast values(13,10,2);
insert into cast values(13,14,3);
insert into cast values(14,11,1);
insert into cast values(14,10,2);
insert into cast values(14,14,3);
insert into cast values(15,8,1);
insert into cast values(15,7,2);
insert into cast values(15,9,3);


